name: tierra_app
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: 1.0.1
  firebase_auth: 3.1.3
  firebase_core: 1.8.0
  firebase_storage: 10.0.6
  flutter:
    sdk: flutter
  flutter_login_facebook: 1.1.0
  get: ^4.3.8
  get_cli: ^1.6.0
  get_storage: ^2.0.3
  google_fonts: 2.1.0
  google_sign_in: 5.1.1
  image_cropper: 1.4.1
  image_picker: 0.8.4+3
  introduction_screen: 2.1.0
  lottie: 1.2.1
  shared_preferences: 2.0.9
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/ss.png"

flutter:
  assets:
    - assets/icons/
    - assets/logo/
    - assets/lottie/
  uses-material-design: true
